version: "3.8"
services: 
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    restart: always
    volumes:
      - "./configs/prometheus:/etc/prometheus:Z"
    
    
  grafana:
    image: docker.io/grafana/grafana
    restart: always
    volumes:
      - "./configs/grafana/provisioning:/etc/grafana/provisioning:Z"
    
