version: "3.8"
services: 
  scapinoculars:
    image: ghcr.io/jritter/scapinoculars:latest
    restart: always
    volumes:
      - "./resources/reports:/opt/go/resources/reports:Z"
    ports:
      - "2112:2112"

  scapinoculars-prometheus:
    image: quay.io/prometheus/prometheus:latest
    restart: always
    volumes:
      - "./configs/prometheus:/etc/prometheus:Z"
    ports:
      - "9090:9090"
  
  scapinoculars-grafana:
    image: docker.io/grafana/grafana
    restart: always
    volumes:
      - "./configs/grafana/provisioning:/etc/grafana/provisioning:Z"
    ports:
      - "3000:3000"
