{
 "title": "SCAPinoculars OpenSCAP Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "OpenSCAP Target",
    "query": {
     "query": "label_values(openscap_results,target)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(openscap_results,severity)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Check status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"openscap_result\", openscap_results{target=~\"$target\", severity=~\"$severity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Rules by Severity",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (openscap_results{target=~\"$target\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Rules",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "openscap_results{target=~\"$target\", severity=~\"$severity\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}