apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus    
    orgId: 1
    url: http://scapinoculars-prometheus:9090
    version: 1
    editable: false
