name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v9

  gotestbuild:
    name: Go Test Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  containerdevbuild:
    name: Container Image Build (:dev)
    runs-on: ubuntu-latest
    needs: gotestbuild
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository_owner }}/scapinoculars
          tags: dev ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          build-args: |
            VERSION=dev
            HASH=${{ github.sha }}

      - name: Login to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
