name: Publish (main)

on:
  push:
    branches: main

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/jritter/openscap-report-publisher:latest
          platforms: linux/amd64
          build-args: |
            VERSION=main
            HASH=${{ github.sha }}